<?php

/**
 * Implements hook_theme().
 */
function drupalbristol_organisers_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['organiser'] = [
    'render element' => 'elements',
    'file' => 'organiser.page.inc',
    'template' => 'organiser',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function drupalbristol_organisers_theme_suggestions_organiser(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#organiser'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'organiser__' . $sanitized_view_mode;
  $suggestions[] = 'organiser__' . $entity->bundle();
  $suggestions[] = 'organiser__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'organiser__' . $entity->id();
  $suggestions[] = 'organiser__' . $entity->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}
