<?php

/**
 * @file
 * Contains drupalbristol_sponsors.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupalbristol_sponsors_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupalbristol_sponsors module.
    case 'help.page.drupalbristol_sponsors':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function drupalbristol_sponsors_theme() {
  $theme = [];
  $theme['sponsor'] = [
    'render element' => 'elements',
    'file' => 'sponsor.page.inc',
    'template' => 'sponsor',
  ];
  $theme['sponsor_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'sponsor.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function drupalbristol_sponsors_theme_suggestions_sponsor(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#sponsor'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'sponsor__' . $sanitized_view_mode;
  $suggestions[] = 'sponsor__' . $entity->bundle();
  $suggestions[] = 'sponsor__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'sponsor__' . $entity->id();
  $suggestions[] = 'sponsor__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
